<?php
include"koneksi.php";

if(is_numeric($_POST['tlp'])==False){
header("location:index.php?page=form_input_cst.php&&tipe=nom&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&top=$_POST[top]&&message=gagal");
}else if(is_numeric($_POST['pokok_hutang'])==False){
header("location:index.php?page=form_input_cst.php&&tipelong=nom&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&top=$_POST[top]&&message=gagal");
}else if(is_numeric($_POST['angsuran'])==False){
header("location:index.php?page=form_input_cst.php&&tipelang=nom&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&top=$_POST[top]&&message=gagal");
}else if($_POST['nkontrak']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['nama']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['tmp_lahir']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['tgl_lahir']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['almt']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['daerah']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['tmp_tagih']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['daerah_tagih']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['tlp']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['pokok_hutang']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['angsuran']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['tgl_jth_tempo']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['top']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}else if($_POST['komen']==""){
header("location:index.php?page=form_input_cst.php&&nkontrak=$_POST[nkontrak]&&nama=$_POST[nama]&&tmp_lahir=$_POST[tmp_lahir]&&tgl_lahir=$_POST[tgl_lahir]&&almt=$_POST[almt]&&daerah=$_POST[daerah]&&agama=$_POST[agama]&&status=$_POST[status]&&warganegara=$_POST[warganegara]&&tmp_tagih=$_POST[tmp_tagih]&&daerah_tagih=$_POST[daerah_tagih]&&tlp=$_POST[tlp]&&pokok_hutang=$_POST[pokok_hutang]&&angsuran=$_POST[angsuran]&&tgl_jth_tempo=$_POST[tgl_jth_tempo]&&komen=$_POST[komen]&&top=$_POST[top]&&message=gagal");
}

else {

mysql_query("insert into cst values ('$_POST[nkontrak]', '$_POST[nama]', '$_POST[tmp_lahir]', '$_POST[tgl_lahir]', '$_POST[almt]', '$_POST[daerah]', '$_POST[agama]', '$_POST[status]', '$_POST[warganegara]', '$_POST[tmp_tagih]','$_POST[daerah_tagih]', '$_POST[tlp]', '$_POST[pokok_hutang]', '$_POST[angsuran]','$_POST[tgl_jth_tempo]','$_POST[komen]','$_POST[top]')");
header("location:index.php?page=tampil_cst2.php");
}?>